"""initialize

Revision ID: 96665d0e1a32
Revises:
Create Date: 2025-05-23 22:52:07.316597

"""

from typing import Union, Sequence

import sqlmodel
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96665d0e1a32"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()


def upgrade_user_center() -> None:
    """Upgrade user_center schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_name"), "account", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade_user_center() -> None:
    """Downgrade user_center schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_name"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###


def upgrade_second() -> None:
    """Upgrade second schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secondtable1",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("a", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("b", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_secondtable1_a"), "secondtable1", ["a"], unique=True)
    op.create_index(op.f("ix_secondtable1_b"), "secondtable1", ["b"], unique=True)
    # ### end Alembic commands ###


def downgrade_second() -> None:
    """Downgrade second schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secondtable1_b"), table_name="secondtable1")
    op.drop_index(op.f("ix_secondtable1_a"), table_name="secondtable1")
    op.drop_table("secondtable1")
    # ### end Alembic commands ###
